### ISSUE TITLE
1.1: missing git tag?

### ISSUE THREAD

**Issue by kloczek** [mozeq/fros#14]
Looks like 1.1. version has been released but there is no git tag.

Or if 1.1 still is not released is it possible to release it?

Thx :)

**Comment by mozeq** [comment]
Hi,
The version 1.1 is the latest master.
I no longer maintain this code - feel free to fork it and make the release yourself if you need it.

**Comment by kloczek** [comment]
OK so could you pelase add to you repo "1.1" tag? :)

**Comment by kloczek** [comment]
As well I think that if you don't want to maintain that code I think that maybe it would be good to add in module description note that you are looking for new maintainer. Than if you will find someone you can transfer repo to somone else.

PS. Happy Easter :)
